name: Build Docs

on:
  pull_request:
    branches:
      - "main"

jobs:
  docs-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: node common/scripts/install-run-rush.js install --ignore-hooks

      - name: Build Docs
        run: node common/scripts/install-run-rush.js build -t @mwap/docs --verbose
        env:
          CI: true

      - name: Export Docs
        run: |
          cd docs
          node ../common/scripts/install-run-rushx.js export
