name: Deploy Docs

on:
  push:
    branches: [main]

jobs:
  docs-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: node common/scripts/install-run-rush.js install --ignore-hooks

      - name: Build Docs
        run: node common/scripts/install-run-rush.js build -t @mwap/docs --verbose

      - name: Export Docs
        run: |
          cd docs
          node common/scripts/install-run-rushx.js export

      - name: Deploy Docs 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: docs/static
