name: Publish Packages

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          always-auth: true
          registry-url: https://registry.npmjs.org
          scope: '@mwap'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Install Dependencies
        run: node common/scripts/install-run-rush.js install --ignore-hooks

      - name: Ensure Version Bump
        run: |
          node common/scripts/install-run-rush.js change -v
          node common/scripts/install-run-rush.js check

      - name: Build
        run: node common/scripts/install-run-rush.js build --verbose

      - name: Version bump
        run: node common/scripts/install-run-rush.js version --bump --target-branch master --ignore-git-hooks

#      - name: Publish
#        run: node common/scripts/install-run-rush.js publish --apply --publish --include-all -target-branch master --add-commit-details --ignore-git-hooks